services:
  db:
    image: bitnami/postgresql
    restart:  always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: chibatex
      POSTGRES_PASSWORD: chibatexAdmin
      POSTGRES_DB: chibatexDatabase
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache_morimitsu
    restart:  always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data


volumes:
  db:
    driver: local
  redis_data:
    driver: local